name: Deploy Staging
on:
  push:
    branches:
      - "staging"
    paths-ignore:
      - '**/README.md'
      - '**/workflows/**'
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: npm ci
      - name: Build
        run:  |
          cp src/env.staging.ts src/env.ts;
          npm run build
      - name: Deploy
        uses: reggionick/s3-deploy@v3.1.1
        with:
          folder: dist
          bucket: ${{ secrets.S3_BUCKET_CURATORFORM_STAGING}}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_CURATORFORM_STAGING }}
          invalidation: /*
          delete-removed: true
      - name: Notify Slack
        if: always()
        uses: edge/simple-slack-notify@master
        with:
          channel: "#deployment-updates"
          color: 'good'
          text: "A new version of the <https://leo.staging.ror.org|LEO FORM> is deployed to staging."
          failure_text: '${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) build failed'
          fields: |
            [{ "title": "Commit message", "value": "${{ steps.extract_variables.outputs.MESSAGE }}" },
             { "title": "Committed by", "value": "<https://github.com/${{ github.repository }}/commits?author=${{ github.actor }}|${{ github.actor }}>", "short": true },
             { "title": "Commit SHA", "value": "<https://github.com/${{ github.repository }}/commit/${{ steps.extract_variables.outputs.GIT_SHA }}|${{ steps.extract_variables.outputs.GIT_SHA_SHORT }}>", "short": true },
             { "title": "Repository", "value": "<https://github.com/${{ github.repository }}|${{ github.repository }}>", "short": true },
             { "title": "Branch", "value": "<https://github.com/${{ github.repository }}/tree/${{ steps.extract_variables.outputs.BRANCH }}|${{ steps.extract_variables.outputs.BRANCH }}>", "short": true }]
